# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import image_360_pb2 as image__360__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in image_360_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Image360ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create360Image = channel.unary_stream(
                '/Image360Service/Create360Image',
                request_serializer=image__360__pb2.CreateImage360Request.SerializeToString,
                response_deserializer=image__360__pb2.CreateImage360Response.FromString,
                _registered_method=True)
        self.Get360Image = channel.unary_stream(
                '/Image360Service/Get360Image',
                request_serializer=image__360__pb2.GetImage360Request.SerializeToString,
                response_deserializer=image__360__pb2.GetImage360Response.FromString,
                _registered_method=True)
        self.GetImagesZip = channel.unary_stream(
                '/Image360Service/GetImagesZip',
                request_serializer=image__360__pb2.GetImagesZipRequest.SerializeToString,
                response_deserializer=image__360__pb2.GetImagesZipResponse.FromString,
                _registered_method=True)


class Image360ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create360Image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get360Image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImagesZip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Image360ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create360Image': grpc.unary_stream_rpc_method_handler(
                    servicer.Create360Image,
                    request_deserializer=image__360__pb2.CreateImage360Request.FromString,
                    response_serializer=image__360__pb2.CreateImage360Response.SerializeToString,
            ),
            'Get360Image': grpc.unary_stream_rpc_method_handler(
                    servicer.Get360Image,
                    request_deserializer=image__360__pb2.GetImage360Request.FromString,
                    response_serializer=image__360__pb2.GetImage360Response.SerializeToString,
            ),
            'GetImagesZip': grpc.unary_stream_rpc_method_handler(
                    servicer.GetImagesZip,
                    request_deserializer=image__360__pb2.GetImagesZipRequest.FromString,
                    response_serializer=image__360__pb2.GetImagesZipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Image360Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Image360Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Image360Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create360Image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Image360Service/Create360Image',
            image__360__pb2.CreateImage360Request.SerializeToString,
            image__360__pb2.CreateImage360Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get360Image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Image360Service/Get360Image',
            image__360__pb2.GetImage360Request.SerializeToString,
            image__360__pb2.GetImage360Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImagesZip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Image360Service/GetImagesZip',
            image__360__pb2.GetImagesZipRequest.SerializeToString,
            image__360__pb2.GetImagesZipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
