# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model3d.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model3d.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmodel3d.proto\"3\n\x11Model3dGenRequest\x12\x0f\n\x07prompts\x18\x01 \x03(\t\x12\r\n\x05title\x18\x02 \x01(\t\"!\n\x11Model3dGetRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\"\n\x12Model3dGetResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"d\n\x12Model3dGenResponse\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x05\x12\x0c\n\x04path\x18\x05 \x03(\t2\x85\x01\n\x11GenModel3dService\x12\x37\n\nGenModel3d\x12\x12.Model3dGenRequest\x1a\x13.Model3dGenResponse0\x01\x12\x37\n\nGetModel3d\x12\x12.Model3dGetRequest\x1a\x13.Model3dGetResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model3d_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODEL3DGENREQUEST']._serialized_start=17
  _globals['_MODEL3DGENREQUEST']._serialized_end=68
  _globals['_MODEL3DGETREQUEST']._serialized_start=70
  _globals['_MODEL3DGETREQUEST']._serialized_end=103
  _globals['_MODEL3DGETRESPONSE']._serialized_start=105
  _globals['_MODEL3DGETRESPONSE']._serialized_end=139
  _globals['_MODEL3DGENRESPONSE']._serialized_start=141
  _globals['_MODEL3DGENRESPONSE']._serialized_end=241
  _globals['_GENMODEL3DSERVICE']._serialized_start=244
  _globals['_GENMODEL3DSERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
